"""api_cache table

Revision ID: 4e7677bfd83f
Revises: a98e460ef740
Create Date: 2026-06-10 01:17:47.925205
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e7677bfd83f'
down_revision: Union[str, None] = 'a98e460ef740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_cache_cache_key'), 'api_cache', ['cache_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_cache_cache_key'), table_name='api_cache')
    op.drop_table('api_cache')
    # ### end Alembic commands ###
