"""subscriber unsubscribe token

Revision ID: a98e460ef740
Revises: e27a37a8cbe6
Create Date: 2026-06-09 17:56:21.451482
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a98e460ef740'
down_revision: Union[str, None] = 'e27a37a8cbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('token', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_subscribers_token'), 'subscribers', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_token'), table_name='subscribers')
    op.drop_column('subscribers', 'token')
    # ### end Alembic commands ###
