"""elo + simulation tables

Revision ID: b6fc2d5408df
Revises: cf6ad4cdc185
Create Date: 2026-06-09 16:09:44.319572
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b6fc2d5408df'
down_revision: Union[str, None] = 'cf6ad4cdc185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('advance_prob', sa.Float(), nullable=False),
    sa.Column('round16_prob', sa.Float(), nullable=False),
    sa.Column('quarter_prob', sa.Float(), nullable=False),
    sa.Column('semi_prob', sa.Float(), nullable=False),
    sa.Column('final_prob', sa.Float(), nullable=False),
    sa.Column('champion_prob', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_run_id'), 'simulation_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_simulation_results_team_id'), 'simulation_results', ['team_id'], unique=False)
    op.add_column('team_strengths', sa.Column('elo', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_strengths', 'elo')
    op.drop_index(op.f('ix_simulation_results_team_id'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_run_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
