"""squads: coaches, players, discrepancies

Revision ID: eb8b6fb1e92f
Revises: eced65242fa5
Create Date: 2026-06-09 15:07:04.879388
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eb8b6fb1e92f'
down_revision: Union[str, None] = 'eced65242fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nationality', sa.String(length=60), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'INJURED', 'SUSPENDED', 'DOUBTFUL', 'OUT', 'UNKNOWN', name='playerstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaches_team_id'), 'coaches', ['team_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=120), nullable=False),
    sa.Column('player_position', sa.Enum('GK', 'DEF', 'MID', 'FWD', 'UNKNOWN', name='position_enum'), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('club', sa.String(length=120), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('role', sa.Enum('STARTER', 'SUBSTITUTE', 'RESERVE', 'UNKNOWN', name='squadrole'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'INJURED', 'SUSPENDED', 'DOUBTFUL', 'OUT', 'UNKNOWN', name='playerstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_normalized_name'), 'players', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('squad_discrepancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('team_code', sa.String(length=3), nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('entity_name', sa.String(length=120), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('chosen_value', sa.String(length=120), nullable=True),
    sa.Column('agreement', sa.Float(), nullable=False),
    sa.Column('by_source', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squad_discrepancies_sync_run_id'), 'squad_discrepancies', ['sync_run_id'], unique=False)
    op.create_index(op.f('ix_squad_discrepancies_team_code'), 'squad_discrepancies', ['team_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_squad_discrepancies_team_code'), table_name='squad_discrepancies')
    op.drop_index(op.f('ix_squad_discrepancies_sync_run_id'), table_name='squad_discrepancies')
    op.drop_table('squad_discrepancies')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_normalized_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_coaches_team_id'), table_name='coaches')
    op.drop_table('coaches')
    # ### end Alembic commands ###
